language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt -r tests/requirements.txt

script:
  - PYTHONPATH=. python tests/nldecap_tests.py
  # 1 = fatal error, 2 = error, 32 = usage error
  - (pylint nldecap.py; exit $(($? & $((1 + 2 + 32)))))
