language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt -r tests/requirements.txt

script:
  # Unit tests
  - PYTHONPATH=. python tests/nldecap_tests.py

  # linters
  # Pylint exit codes contain 1 on fatal errors, 2 on errors and 32 on usage errors
  - (pylint nldecap.py; exit $(($? & $((1 + 2 + 32)))))
  - (pylint tests/nldecap_tests.py; exit $(($? & $((1 + 2 + 32)))))
  - pycodestyle --max-line-length=80 nldecap.py
  - pycodestyle --max-line-length=80 tests/nldecap_tests.py
